# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [67]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [68]:
print(np.__version__)
np.show_config()

2.1.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd


#### 3. Create a null vector of size 10 (★☆☆)

In [69]:
null = np.zeros(10)
print(null)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [70]:
array = np.array([1, 2, 3])
print(array.nbytes)

24


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [71]:
null1 = np.zeros(10)
null1[4] = 1
print(null1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [72]:
array1 = np.arange(start=10, stop=50)
print(array1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [73]:
array2 = array1[::-1]
print(array2)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [74]:
array3 = np.arange(9)
array4 = array3.reshape(3,3)
print(array4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [75]:
array5 = np.array([1,2,0,0,4,0])
np.nonzero(array5)

(array([0, 1, 4]),)

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [76]:
matrix = np.identity(3)
print(matrix)

matrix1 = np.eye(3)
print(matrix1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [77]:
rv = np.random.random((3,3,3))
print(rv)

[[[0.46903596 0.39709462 0.73121036]
  [0.96475786 0.14310166 0.33766926]
  [0.07836913 0.74894379 0.65815336]]

 [[0.98135793 0.489729   0.5275367 ]
  [0.68452524 0.07561026 0.27140369]
  [0.42765869 0.73000224 0.92221247]]

 [[0.95183935 0.97913656 0.69046667]
  [0.56335256 0.04777871 0.82318511]
  [0.20884104 0.88922145 0.42583586]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [78]:
rv10 = np.random.random((10,10))
print(rv10)
print(rv10.min())
print(rv10.max())

[[0.84693446 0.73792447 0.68271444 0.84340727 0.83984475 0.29719034
  0.8152724  0.42097443 0.19742103 0.50719731]
 [0.81331494 0.44029574 0.18905389 0.91649865 0.56988897 0.49244436
  0.89160367 0.00381604 0.22840479 0.96295342]
 [0.52143233 0.41566868 0.0977425  0.89938735 0.13412341 0.91692684
  0.71579745 0.6163252  0.83259931 0.12329554]
 [0.50306482 0.76943345 0.07016798 0.21867977 0.35442639 0.66890577
  0.6736739  0.42230078 0.17326322 0.3146247 ]
 [0.83933327 0.58698819 0.06382542 0.66076258 0.63281735 0.1221948
  0.82623077 0.16221674 0.2431085  0.16509467]
 [0.97731346 0.06052554 0.54093687 0.78824528 0.20098443 0.94637499
  0.33885662 0.54146112 0.62897701 0.44608682]
 [0.14392743 0.44249393 0.96862311 0.98386398 0.13696672 0.63071995
  0.40319002 0.63244585 0.76596924 0.59039881]
 [0.7239887  0.77331419 0.85837028 0.09479021 0.54060173 0.5458332
  0.08325977 0.52126921 0.57669762 0.01043772]
 [0.01757425 0.05471629 0.02949795 0.61787789 0.73015115 0.48178468
  0.79696793 0

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [79]:
rv30 = np.random.random(30)
print(rv30)
print(rv30.mean())

[0.3553545  0.34535222 0.04292335 0.84023681 0.64480252 0.47772422
 0.03223928 0.96608995 0.34248245 0.01093138 0.76622462 0.05986044
 0.63429907 0.84702134 0.83909212 0.26364168 0.56653533 0.72943588
 0.59119957 0.89423962 0.78871099 0.15254896 0.85378279 0.84410629
 0.25642823 0.20670531 0.47886862 0.1328699  0.75203272 0.10287974]
0.49395399651446964


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [80]:
array2d = np.ones((3,3))

In [81]:
array2d[1:-1, 1:-1] = 0
print(array2d)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [82]:
mat5 = np.zeros((5,5))
mat5[1,0] = 1
mat5[2,1] = 2
mat5[3,2] = 3
mat5[4,3] = 4
print(mat5)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [83]:
check = np.zeros((8,8))
check[::2, ::2] = 1
check[1::2, 1::2] = 1
print(check)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [84]:
np.unravel_index(99, (6,7,8))

(np.int64(1), np.int64(5), np.int64(3))

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [85]:
nor = np.random.random((5,5))
z = (nor - nor.mean()) / nor.std()
print(z)

[[ 1.03529326  0.96655104  1.55777444 -0.04826626 -0.77427436]
 [ 1.6548691   0.27997634 -0.96201449 -0.90509168 -1.31638573]
 [ 1.18723264  1.40866484  0.15791643  1.67048585 -1.19935061]
 [-0.82807334  0.15014027 -0.87297278 -0.32932317  0.31299386]
 [-1.33053914  0.35809134 -0.0122725  -0.84423851 -1.31718685]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [86]:
color = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])
print(color)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 3

In [ ]:
# column 2


In [ ]:
# column 3
